apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  DB_HOST: "mysql"
  DB_NAME: "contacts_app"
  DB_PORT: "3306"

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  DB_User: "cm9vdA=="  # Base64-encoded 'root'
  DB_Password: "YWRtaW4="  # Base64-encoded 'admin'
